version: '3.2'

services:

  php:
    build: .
    ports:
      - "13080:80"
    container_name: yii-php
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    links:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=yii
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=password
    ports:
      - "33013:3306"
    container_name: yii-mysql
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci

  redis:
    image: redis:3.0
    volumes:
      - ./docker/redis:/data
    ports:
      - "63713:6379"
    container_name: yii-redis